---
opennms_image_version: '19.0.1-1'
postgres_image_version: '9.5'
service_description: 'OpenNMS Horizon Application Stack {{ opennms_image_version }}'
working_dir: '/opt/docker/opennms'
service_name: 'opennms-horizon-stack'
service_friendly_name: 'OpenNMS Horizon Application Stack {{ opennms_image_version }}'

timezone: 'Europe/Berlin'

postgres_port: '5432'
postgres_user: 'postgres'
postgres_password: 'postgres'
postgres_port_expose: '5432:5432'

opennms_dbname: 'opennms'
opennms_dbuser: 'opennms'
opennms_dbpass: 'opennms'
opennms_home: '/opt/opennms'
opennms_db_config: '/opt/opennms/etc/opennms-datasources.xml'

opennms_volume_etc: '/opt/opennms-etc:/opt/opennms/etc'
opennms_config_version: 'master'

opennms_webui_port_expose: '8980:8980'
opennms_jmx_port_expose: '18980:18980'
opennms_rmi_port_expose: '1099:1099'
opennms_karaf_port_expose: '8101:8101'
opennms_activemq_port_expose: '61616:61616'
opennms_eventd_port_expose: '5817:5817'
opennms_trap_port_expose: '162:162/udp'
